.\"                                      -*- nroff -*-
.\" icp.1 - Manual page for icp.
.\"
.\" Copyright (C) 2001, 2002, 2004, 2005 Oskar Liljeblad
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Library General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
.\"
.TH ICP "1" "August 12, 2005" "icp (renameutils)"
.SH NAME
icp \- Copy a file by editing the destination name using GNU readline
.SH SYNOPSIS
.B icp
.RI [ OPTION ] " FILE"...
.SH DESCRIPTION
This manual page document describes the \fBicp\fP command.

\fBicp\fP is a program to interactively copy a single file.
It does this by allowing the file name to be edited inline
with GNU readline. This is very similar to using \fBcp\fP(1) and
editing the filename on the shell command-line, with one
exception - the filename does not have to be typed twice.

The \fBicp\fP program executes \fBcp\fP(1) to do the actual renaming.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').

All options passed to \fBicp\fP except those listed below are passed to
\fBcp\fP.
.TP
.B \-\-help
Show summary of options.
.TP
.B \-\-version
Output version information and exit.
.SH REPORTING BUGS
Report bugs to <\fIoskar@osk.mine.nu\fP>.
.SH SEE ALSO
\fBcp\fP(1)
.SH AUTHOR
The author of \fBrenameutils\fP and this manual page is Oskar Liljeblad <\fIoskar@osk.mine.nu\fP>.
.SH COPYRIGHT
Copyright \(co 2001, 2002, 2004, 2005 Oskar Liljeblad

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
